[project]
name = "spend-cli"
version = "0.1.0"
description = "A command-line expense tracker"
readme = "README.md"
authors = [
    { name = "Daria Doronina", email = "skidle.dd@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
spend = "spend.cli:main"

[tool.uv.build-backend]
module-name = "spend"

[tool.mypy]
strict = true

[tool.ruff.lint.isort]
known-first-party = ["spend"]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "ruff>=0.16.4",
]
